### PR TITLE
Changing the API to be Async

### PR DESCRIPTION
**Pull request by patnaikshekhar**
Changed all APIs to be async

- Updated code for client
- Bumped all dependencies to latest value 
- Included Tokio as a DevDep
- Fixed Tests
- Updated Readme
- Updated Examples

### CODE REVIEW

**Comment by patnaikshekhar** [comment]
@tzmfreedom could you have a look at this one as well. It fixes issue #2

**Comment by tzmfreedom** [comment]
@patnaikshekhar Thank you for your help!!
I Travis CI is failure on this PR. 
https://travis-ci.com/github/tzmfreedom/rustforce/builds/178548412

Do you know the reason??

**Comment by patnaikshekhar** [comment]
@tzmfreedom I think its because of the version of rust. I've tried to bump the version to 1.44. However I think Travis has cached the old version.

**Review by tzmfreedom — APPROVED** [review]
@patnaikshekhar Thank you!!

**Pull request merged**
